name: Build and Release Live USB Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create Git tag
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          git tag $TAG
          git push origin $TAG

      - name: Install required tools
        run: sudo apt-get update && sudo apt-get install -y util-linux gzip

      - name: Change directory to .files
        working-directory: .files
        run: |
          cat sdb2.img.gz.part-aa sdb2.img.gz.part-ab > sdb2.img.gz
          gzip -dk sdb1.img.gz sdb2.img.gz sdb3.img.gz

      - name: Move extracted images to root
        run: mv .files/*.img ./

      - name: Create empty full image file
        run: dd if=/dev/zero of=PeDitXEZOs.img bs=1M count=1500

      - name: Setup loop device with partitions
        id: losetup
        run: |
          LOOP_DEV=$(sudo losetup --find --show --partscan PeDitXEZOs.img)
          echo "loopdev=$LOOP_DEV" >> $GITHUB_OUTPUT

      - name: Apply partition table to loop device
        run: |
          sudo sfdisk ${{ steps.losetup.outputs.loopdev }} < partition-table.txt || true

      - name: Write partitions into image loop device
        run: |
          sudo dd if=sdb1.img of=${{ steps.losetup.outputs.loopdev }}p1 bs=1M status=progress
          sudo dd if=sdb2.img of=${{ steps.losetup.outputs.loopdev }}p2 bs=1M status=progress
          sudo dd if=sdb3.img of=${{ steps.losetup.outputs.loopdev }}p3 bs=1M status=progress

      - name: Detach loop device
        run: sudo losetup -d ${{ steps.losetup.outputs.loopdev }}

      - name: Compress final image
        run: gzip -k PeDitXEZOs.img

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: PeDitXEZOs.img.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
